"""empty message

Revision ID: 00508779e2a8
Revises: f2ce420ef1ab
Create Date: 2020-09-18 20:24:39.586879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00508779e2a8'
down_revision = 'f2ce420ef1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
